#!/usr/bin/env python3
"""Generate Rook's OpenRouter model catalog from the official Models API."""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any


API_URL = "https://openrouter.ai/api/v1/models"
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "src" / "config" / "openrouter_catalog.rv"


def read_catalog(source: str) -> dict[str, Any]:
    """Read a catalog response from an HTTP endpoint or local JSON file."""
    if source.startswith(("http://", "https://")):
        request = urllib.request.Request(
            source,
            headers={
                "Accept": "application/json",
                "User-Agent": "rook-catalog-sync/1.0",
            },
        )
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.load(response)

    with Path(source).open(encoding="utf-8") as handle:
        return json.load(handle)


def model_records(document: Any) -> list[tuple[int, str, bool]]:
    """Validate and order model IDs with their advertised tool support."""
    if not isinstance(document, dict):
        raise ValueError("OpenRouter response must be a JSON object")
    data = document.get("data")
    if not isinstance(data, list):
        raise ValueError("OpenRouter response is missing a data array")

    models: list[tuple[int, str, bool]] = []
    seen: set[str] = set()
    for entry in data:
        if not isinstance(entry, dict):
            raise ValueError("OpenRouter response contains a non-object model")

        model_id = entry.get("id")
        if not isinstance(model_id, str) or not model_id or "/" not in model_id:
            raise ValueError(f"invalid OpenRouter model id: {model_id!r}")
        if model_id in seen:
            raise ValueError(f"duplicate OpenRouter model id: {model_id}")
        seen.add(model_id)

        created = entry.get("created", 0)
        if not isinstance(created, int):
            created = 0
        supported = entry.get("supported_parameters", [])
        if not isinstance(supported, list):
            raise ValueError(
                f"invalid supported_parameters for OpenRouter model: {model_id}"
            )
        models.append((created, model_id, "tools" in supported))

    models.sort(key=lambda model: (-model[0], model[1]))
    return models


def model_ids(document: Any) -> list[str]:
    """Return validated, deduplicated model IDs newest first."""
    return [model_id for _, model_id, _ in model_records(document)]


def model_ids_without_tools(document: Any) -> list[str]:
    """Return models that do not advertise the OpenRouter tools parameter."""
    return [
        model_id
        for _, model_id, supports_tools in model_records(document)
        if not supports_tools
    ]


def render(models: list[str], models_without_tools: list[str] | None = None) -> str:
    """Render model IDs and tool capability as generated Raven functions."""
    no_tools = models_without_tools or []
    lines = [
        "// Generated by scripts/sync_openrouter_catalog.py from",
        (
            f"// {API_URL}. Contains {len(models)} models, including "
            f"{len(no_tools)} without advertised tool support. Do not edit by hand."
        ),
        "",
        "fun openrouter_catalog() -> List<String> {",
        "    return [",
    ]
    for model_id in models:
        lines.append(f"        {json.dumps(f'openrouter/{model_id}')},")
    lines.extend(
        [
            "    ]",
            "}",
            "",
            "fun openrouter_models_without_tools() -> List<String> {",
            "    return [",
        ]
    )
    for model_id in no_tools:
        lines.append(f"        {json.dumps(f'openrouter/{model_id}')},")
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def main() -> int:
    """Run the catalog sync command."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        default=API_URL,
        help="OpenRouter Models API URL or a local JSON response",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="generated Raven module",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the generated output differs without writing it",
    )
    args = parser.parse_args()

    try:
        document = read_catalog(args.source)
        models = model_ids(document)
        no_tools = model_ids_without_tools(document)
        output = render(models, no_tools)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"catalog sync failed: {error}", file=sys.stderr)
        return 1

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != output:
            print(f"{args.output} is out of date", file=sys.stderr)
            return 1
        print(f"{args.output} is up to date")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    print(f"wrote {len(models)} models to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
